services:
  # Backend API
  - type: web
    name: dvinte-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && yarn dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: APP_SECRET
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: dvinte-backend
          property: host
      - key: FRONTEND_URL
        sync: false

  # Frontend Static Site
  - type: web
    name: dvinte-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: dvinte-backend
          property: host
